#define WIDTH 6
#define HEIGHT 6
#define WL (char)0xFF
#define EP (char)0x00
static char mznd[]={
    WL,WL,WL,EP, WL,EP,EP,WL, WL,EP,WL,WL, WL,EP,WL,EP, WL,WL,EP,EP, WL,WL,EP,WL,
    WL,EP,WL,EP, EP,EP,EP,WL, EP,EP,WL,EP, EP,WL,EP,EP, WL,WL,EP,WL, WL,EP,WL,WL,
    EP,EP,WL,WL, EP,WL,WL,EP, EP,EP,EP,EP, WL,WL,EP,EP, WL,WL,EP,EP, EP,EP,EP,WL,
    EP,WL,WL,WL, WL,EP,WL,EP, EP,EP,EP,WL, WL,WL,WL,EP, WL,WL,EP,EP, EP,EP,EP,WL,
    WL,EP,WL,WL, EP,EP,WL,WL, EP,WL,WL,EP, WL,EP,EP,WL, WL,EP,WL,WL, EP,EP,WL,WL,
    EP,WL,WL,EP, EP,WL,EP,EP, WL,WL,EP,WL, EP,WL,WL,WL, EP,WL,WL,EP, EP,WL,EP,WL};
